name: megabucks_tournament_manager

services:
  api:
    container_name: tournament_manager_api
    image: tournament-manager-api
    build:
      context: .
      dockerfile: src/BowlingMegabucks.TournamentManager.Api/Dockerfile
    ports:
      - 5100:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_DOCKER_JSON: true
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://telemetry:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  telemetry:
    container_name: megabucks_tournament_manager_telemetry
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    restart: always
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
      DASHBOARD__TELEMETRYLIMITS__MAXLOGCOUNT: 1000
      DASHBOARD__TELEMETRYLIMITS__MAXTRACECOUNT: 1000
      DASHBOARD__TELEMETRYLIMITS__MAXMETRICSCOUNT: 1000
    ports:
      - 18888:18888
      - 4317:18889
  database:
    container_name: megabucks_tournament_manager_database
    image: mariadb:11.4.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123!
      MYSQL_DATABASE: tournament_manager
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password_123!
    ports:
      - "23306:3306"
    volumes:
      - megabucks_tournament_manager_data:/var/lib/mysql
      - ./.docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  megabucks_tournament_manager_data:
