// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BowlingMegabucks.TournamentManager.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class TournamentEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Tournaments",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "char(36)", nullable: false, comment: "Unique identifier for the tournament", collation: "ascii_general_ci"),
                    Name = table.Column<string>(type: "varchar(150)", maxLength: 150, nullable: false, comment: "Name of the tournament")
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    StartDate = table.Column<DateOnly>(type: "date", nullable: false, comment: "Start date of the tournament"),
                    EndDate = table.Column<DateOnly>(type: "date", nullable: false, comment: "End date of the tournament"),
                    EntryFee = table.Column<decimal>(type: "decimal(5,2)", precision: 5, scale: 2, nullable: false, comment: "Entry fee for the tournament"),
                    Games = table.Column<short>(type: "smallint", nullable: false, comment: "Number of games during qualifying in the tournament"),
                    FinalsRatio = table.Column<decimal>(type: "decimal(3,1)", precision: 3, scale: 1, nullable: false, comment: "Finals ratio for the tournament"),
                    CashRatio = table.Column<decimal>(type: "decimal(3,1)", precision: 3, scale: 1, nullable: false, comment: "Cash ratio for the tournament"),
                    BowlingCenter = table.Column<string>(type: "varchar(150)", maxLength: 150, nullable: false, comment: "Bowling center hosting the tournament")
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Completed = table.Column<bool>(type: "tinyint(1)", nullable: false, comment: "Indicates if the tournament is completed"),
                    CreatedAt = table.Column<DateTime>(type: "datetime(6)", nullable: false, comment: "UTC timestamp when entity was created"),
                    UpdatedAt = table.Column<DateTime>(type: "datetime(6)", nullable: false, comment: "UTC timestamp when entity was last updated")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tournaments", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Tournaments");
        }
    }
}
