// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewEnglandClassic.Database;

#nullable disable

namespace NewEnglandClassic.Database.Migrations;

[DbContext(typeof(DataContext))]
[Migration("20220430141220_DivisionEntity")]
partial class DivisionEntity
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("NewEnglandClassic.Database.Entities.Division", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<int?>("Gender")
                    .HasColumnType("int");

                b.Property<int?>("HandicapBase")
                    .HasColumnType("int");

                b.Property<decimal?>("HandicapPercentage")
                    .HasColumnType("decimal(65,30)");

                b.Property<short?>("MaximumAge")
                    .HasColumnType("smallint");

                b.Property<int?>("MaximumAverage")
                    .HasColumnType("int");

                b.Property<int?>("MaximumHandicapPerGame")
                    .HasColumnType("int");

                b.Property<short?>("MinimumAge")
                    .HasColumnType("smallint");

                b.Property<int?>("MinimumAverage")
                    .HasColumnType("int");

                b.Property<short>("Number")
                    .HasColumnType("smallint");

                b.Property<Guid>("TournamentId")
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.HasIndex("TournamentId");

                b.ToTable("Divisions");
            });

        modelBuilder.Entity("NewEnglandClassic.Database.Entities.Division", b =>
            {
                b.HasOne("NewEnglandClassic.Database.Entities.Tournament", "Tournament")
                    .WithMany("Divisions")
                    .HasForeignKey("TournamentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tournament");
            });

        modelBuilder.Entity("NewEnglandClassic.Database.Entities.Tournament", b =>
            {
                b.Navigation("Divisions");
            });
#pragma warning restore 612, 618
    }
}
