//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NortheastMegabuck.Database.Migrations
{
    /// <inheritdoc />
    public partial class RegistrationAltKeyToIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropUniqueConstraint(
                name: "AK_Registrations_BowlerId_DivisionId",
                table: "Registrations");

            migrationBuilder.CreateIndex(
                name: "IX_Registrations_BowlerId_DivisionId",
                table: "Registrations",
                columns: new[] { "BowlerId", "DivisionId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Registrations_BowlerId_DivisionId",
                table: "Registrations");

            migrationBuilder.AddUniqueConstraint(
                name: "AK_Registrations_BowlerId_DivisionId",
                table: "Registrations",
                columns: new[] { "BowlerId", "DivisionId" });
        }
    }
}
