name: .Net Build (Pull Request)

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet run --project tests/BowlingMegabucks.TournamentManager.Domain.UnitTests --verbosity normal --configuration Release
    # - name: Integration Tests
    #   run: dotnet run --project source/tests/BowlingMegabucks.TournamentManager.IntegrationTests
