name: .Net Build (WinForm / Unit Tests)

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Clean
      run: dotnet clean source/api --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build source/api --configuration Release
    - name: Integration Tests
      run: dotnet test source/tests/BowlingMegabucks.TournamentManager.IntegrationTests --no-build --verbosity normal --configuration Release