name: .Net Build (Pull Request)

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

env:
  DOTNET_VERSION: '10.x'

# ...existing code...
jobs:
  BuildApi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      - name: Build
        run: dotnet build src/BowlingMegabucks.TournamentManagement.Api --configuration Release

  BuildApp:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  ${{ env.DOTNET_VERSION }}

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      - name: Build
        run: dotnet build src/BowlingMegabucks.TournamentManagement.App --configuration Release

  UnitTests:
    runs-on: ubuntu-latest
    needs: [BuildApi, BuildApp]
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.UnitTests.Domain
          - tests/BowlingMegabucks.TournamentManager.UnitTests.Presentation
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  ${{ env.DOTNET_VERSION }}
      - name: Run Unit Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release

  IntegrationTests:
    runs-on: ubuntu-latest
    needs: [BuildApi, BuildApp]
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.IntegrationTests.Application
          - tests/BowlingMegabucks.TournamentManager.IntegrationTests.Infrastructure
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  ${{ env.DOTNET_VERSION }}
      - name: Run Integration Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release

  FunctionalTests:
    runs-on: ubuntu-latest
    needs: [BuildApi, BuildApp]
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.FunctionalTests
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  ${{ env.DOTNET_VERSION }}
      - name: Run Functional Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release
