name: .Net Build (Pull Request)

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

# ...existing code...
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      - name: Build
        run: dotnet build --configuration Release

  UnitTests:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.UnitTests.Domain
          - tests/BowlingMegabucks.TournamentManager.UnitTests.Presentation
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run Unit Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release

  IntegrationTests:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.IntegrationTests.Application
          - tests/BowlingMegabucks.TournamentManager.IntegrationTests.Infrastructure
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run Integration Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release

  FunctionalTests:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        test_project:
          - tests/BowlingMegabucks.TournamentManager.FunctionalTests
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run Functional Tests
        run: dotnet run --project ${{ matrix.test_project }} --verbosity normal --configuration Release
